nginx:
  image: nginx:latest
  ports:
    - "127.0.0.1:8080:80"
  volumes:
    - .:/app
    - ./.docker/nginx/sungorus.conf:/etc/nginx/conf.d/default.conf
  links:
    - fpm

fpm:
  build: ./
  volumes:
    - .:/app
  links:
    - "db"

composer:
  restart: "no"
  image: composer
  command: install
  volumes:
    - .:/app
    
db:
  image: mysql:5
  volumes:
    - /var/lib/mysql
    - ./.docker/db/structure.sql:/docker-entrypoint-initdb.d/structure.sql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: sungorus
    MYSQL_USER: sungorus
    MYSQL_PASSWORD: sungorus
      
