<div class="row">
    <div class="col-md-4" style="float: none; margin: 10px auto;">
        <div class="panel panel-<?= $error ? 'danger' : 'default'; ?> panel-shadow">
            <div class="panel-heading">
                <h3 class="panel-title">Sign in to Sungorus</h3>
            </div>
            <div class="panel-body">
                <?php
                    $form->setAttribute('action', $this->url('login'));

                    $form->get('submit')->setAttribute('class', 'btn btn-primary btn-block');

                    echo $this->form($form, null);
                ?>
                <?php if ($registration): ?>
                    <div class="text-center text-muted" style="margin-top: 20px;">
                        Don't have an account?
                        <a href="<?= $this->escapeHtmlAttr($this->url('signup')); ?>">Sign up</a>
                    </div>
                <?php endif; ?>
            </div>

        </div>
    </div>
</div>