<div class="row">
    <div class="col-md-4" style="float: none; margin: 10px auto;">
        <div class="panel panel-<?= $error ? 'danger' : 'info'; ?> panel-shadow">
            <div class="panel-heading">
                <h3 class="panel-title">Sign in</h3>
            </div>
            <div class="panel-body">
                <?php if ($message): ?>
                    <div class="alert alert-danger text-center">
                        <?= $this->escapeHtml($message); ?>
                    </div>
                <?php endif; ?>
                <?php 
                    $form->setAttribute('action', $this->url('login'));

                    $form->get('submit')->setAttribute('class', 'btn btn-primary');

                    echo $this->form($form, null);
                ?>
            </div>
        </div>

<?php if ($registrationEnabled): ?>
        <div class="alert alert-info text-center">
            <strong>
                <a href="<?= $this->escapeHtmlAttr($this->url('signup')); ?>">Registration</a>
            </strong>
            is open for everyone!
        </div>
<?php endif; ?>
    </div>
</div>