<?php
$this->headTitle()
     ->append($this->escapeHtml($account->getName()))
     ->append($this->escapeHtml($folder->getName()));
?>

<div class="row">
    <div class="col-md-4">
        <?php echo $this->partial('/application/folder/partials/folders.phtml', [
            'folderId' => $folderId,
            'folders'  => $folders,
        ]); ?>
    </div>
    <div class="col-md-8">
        <div class="panel panel-default panel-shadow">
            <div class="panel-heading">
                <h3 class="panel-title">Account</h3>
            </div>
            <div class="panel-body">
                <?php echo $this->form($form); ?>
            </div>
            <div class="panel-footer dates">
                <strong>Created:</strong>
                <time class="timeago" datetime="<?= $account->getDateCreated(); ?>">
                    <?= $account->getDateCreated(); ?>
                </time>
                <strong>Modified:</strong>
                <time class="timeago" datetime="<?= $account->getDateModified(); ?>">
                    <?= $account->getDateModified(); ?>
                </time>
            </div>
        </div>
    </div>
</div>
<div class="hidden">
    <div class="input-group-btn" id="input-url__append">
        <a class="btn btn-default" title="Open in new window" href="<?php echo $this->escapeHtmlAttr(
            $this->url('folders/folder/accounts/account/openUrl', [], null, true)
        ); ?>" target="_blank" rel="noopener noreferrer">
            <span class="glyphicon glyphicon-new-window"></span>
        </a>
    </div>
    <div class="input-group-btn" id="input-password__append">
        <button type="button" class="btn btn-default" title="Generate password">
            <span class="glyphicon glyphicon-refresh"></span>
        </button>
    </div>
</div>
<script>
    var $passwordBtn = $('input[name="data[password]"]');
    $('#input-password__append button').click(function () {
        $passwordBtn.val(generatePassword());
    });

    $passwordBtn.wrapAll('<div class="input-group"></div>')
        .after($('#input-password__append'));

    $('input[name="data[url]"]').wrapAll('<div class="input-group"></div>')
        .after($('#input-url__append'));
</script>