<div class="list-group accounts-list">
    <?php if (!$accounts->count()): ?>
        <p class="list-group-item list-group-item-warning">Empty folder</p>
    <? endif ?>
    <?php
    foreach ($accounts as $account):
        $params      = array(
            'folderId'  => $account->getFolderId(),
            'accountId' => $account->getId()
        );
        $edit_url    = $this->url('folder/account', $params);
        $delete_url  = $this->url('folder/account/delete', $params);
        $favicon_url = $this->url('folder/account/favicon', $params);
        ?>
        <a href="<?= $edit_url ?>" class="list-group-item">
            <img class="favicon" src="<?= $favicon_url ?>">
            <div class="list-group-item-text actions">
                <span onclick="return deleteAccount('<?= $this->escapeJs($delete_url) ?>', '<?= $this->escapeJs($account->getName()) ?>');" class="link" title="Delete"><span class="glyphicon glyphicon-remove"></span></span>
            </div>

            <? if ($account->getFavorite()): ?>
                <div class="list-group-item-text favorite">
                    &nbsp;<span class="glyphicon glyphicon-star"></span>
                </div>
            <? endif; ?>

            <?= $this->escapeHtml($account->getName()) ?>
        </a>
    <?php endforeach; ?>
</div>
