<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Sungorus ')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/main.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/functions.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.timeago.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
        ;
        ?>
        <script type="text/javascript">
            $(document).ready(function () {
                $('time.timeago').timeago();
            })
        </script>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">Sungorus</a>
                </div>
                <div class="collapse navbar-collapse" id="top-navbar-collapse">

                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <?= $this->escapeHTML($this->identity()->getEmail()) ?>
                                <span class="glyphicon glyphicon-chevron-down" style="font-size: 10px"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="<?= $this->url('export') ?>">Export</a>
                                </li>
                                <li>
                                    <a href="<?= $this->url('auth', ['controller' => 'Auth', 'action' => 'changePassword']) ?>">Change password</a>
                                </li>
                                <li>
                                    <a href="<?= $this->url('auth', ['controller' => 'Auth', 'action' => 'clearEncryptionKey']) ?>">Forget encryption key</a>
                                </li>
                                <li>
                                    <a href="<?= $this->url('logout') ?>">Logout</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <form class="navbar-form navbar-right" role="search" action="<?= $this->url('search') ?>">
                        <div class="form-group">
                            <div class="input-group search-input-group">
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-search"></span>
                                </span>
                                <input type="text" name="name" class="form-control"  placeholder="Search account" >
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->

        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLable" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="deleteModalLable">Please Confirm</h4>
                    </div>
                    <div class="modal-body">
                        Are you sure that you want to delete the "<span class="name"></span>" <span class="item-type"></span>?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-danger btn-confirm">Delete</button>
                    </div>
                </div>
            </div>
        </div>

    </body>
</html>
