<?php
$this->headTitle()->append($this->escapeHtml($folder->getName()));
?>

<div class="row">
    <div class="col-md-4">
        <?=
        $this->partial('/application/folder/partials/folders.phtml', array(
            'folderId' => $folderId,
            'folders'  => $folders,
        ));
        ?>
    </div>
    <div class="col-md-8">
        <div class="panel panel-default panel-shadow">
            <div class="panel-heading">
                <?php if ($folderId): ?>
                    <div class="pull-right">
                        <a href="<?= $this->url('folders/folder/accounts/add', array('folderId' => $folderId)) ?>"><span class="glyphicon glyphicon-plus-sign"></span></a>
                    </div>
                <? endif; ?>
                <h3 class="panel-title">Accounts</h3>
            </div>
            <?=
            $this->partial('/application/folder/partials/accounts.phtml', array(
                'folderId' => $folderId,
                'accounts' => $accounts,
            ));
            ?>
        </div>
    </div>
</div>