<?php
$this->headTitle()->append('Sign up');
?>

<div class="row">
    <div class="col-md-4" style="float: none; margin: 10px auto;">
        <div class="panel panel-default panel-shadow">
            <div class="panel-heading">
                <h3 class="panel-title">Sign up</h3>
            </div>
            <div class="panel-body">
                <?php
                $form->get('submit')->setAttribute('class', 'btn btn-primary');
                echo $this->form($form, null);
                ?>
            </div>
        </div>
    </div>
</div>