<?php
$folderNames = array();
foreach ($folders as $folder) {
    $folderNames[$folder->getId()] = $folder->getName();
}
?>
<div class="row">
    <div class="col-md-4">
        <?=
        $this->partial('/application/folder/partials/folders.phtml', array(
            'folderId' => 0,
            'folders'  => $folders,
        ));
        ?>
    </div>
    <div class="col-md-8">
        <div class="panel panel-default panel-shadow">
            <div class="panel-heading">
                <h3 class="panel-title">Favorites</h3>
            </div>
            <?=
            $this->partial('/application/folder/partials/accounts.phtml', [
                'accounts' => $accounts,
            ]);
            ?>
        </div>

        <?php if (!empty($lastAuth)): ?>
            <div class="alert alert-warning panel-shadow">
                <strong>
                    Last successful login:
                </strong>
                <time class="timeago" datetime="<?php echo $lastAuth->getDatetime(); ?>">
                    <?php echo $lastAuth->getDatetime(); ?>
                </time> from <?php echo long2ip($lastAuth->getIp()); ?>

            </div>
        </div>
    <?php endif; ?>
</div>
</div>